### ISSUE TITLE
Usar session.createCriteria de Hibernate para los queries que requieren filtrar datos

### ISSUE THREAD

**Issue by fdodino** [BordaH/PoS-Ecommerce#1]
Ej: en el login estás trayendo todos los usuarios para luego quedarte con el primero (filtrar en memoria tras traerte todos los usuarios no es una buena estrategia). Utilizar un createCriteria.

**Comment by BordaH** [comment]
Arreglado en el commit 85dc85fcc087f33022f2c150d3f53818e0b4adcf
